[tool.poetry]
name = "kafla-sample"
version = "0.0.1"
package-mode = false

[tool.poetry.dependencies]
python = "3.11.7"
uvicorn = "0.27.1"
kafka-python = "2.0.2"
msgpack = "1.0.8"
requests = "2.32.3"